{
 "title": "Aiven Kafka Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "project",
    "query": {
     "query": "label_values(system_uptime,project)"
    }
   },
   {
    "name": "service",
    "label": "project",
    "query": {
     "query": "label_values(system_uptime,service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Automatically maintained Aiven dashboard - NOTE: Changes here will be lost at the next upgrade",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime (min)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(system_uptime{project=\"$project\", service=\"$service\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Load average (1 min max)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(system_load1{project=\"$project\", service=\"$service\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Memory available (min)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(mem_available{project=\"$project\", service=\"$service\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Disk free (min)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(disk_free{project=\"$project\", service=\"$service\"}[$__interval])) "
    }
   ]
  },
  {
   "title": "System metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(cpu_usage_system{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "{{ host }}.system"
    },
    {
     "expr": "avg by (host)(avg_over_time(cpu_usage_iowait{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "{{ host }}.iowait"
    },
    {
     "expr": "avg by (host)(avg_over_time(cpu_usage_irq{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "{{ host }}.irq"
    },
    {
     "expr": "avg by (host)(avg_over_time(cpu_usage_user{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "{{ host }}.user"
    }
   ]
  },
  {
   "title": "Load average (1 min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max by (host)(max_over_time(system_load1{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Memory available",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "min by (host)(min_over_time(mem_available{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Memory unused",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(mem_free{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Context switches",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(rate(kernel_context_switches{project=\"$project\", service=\"$service\"}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "min by (host)(rate(kernel_interrupts{project=\"$project\", service=\"$service\"}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(processes_blocked{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "blocked.{{ host }}"
    },
    {
     "expr": "avg by (host)(avg_over_time(processes_paging{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "paging.{{ host }}"
    },
    {
     "expr": "avg by (host)(avg_over_time(processes_running{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "running.{{ host }}"
    },
    {
     "expr": "avg by (host)(avg_over_time(processes_zombies{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "zombies.{{ host }}"
    }
   ]
  },
  {
   "title": "Disk free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "min by (path,host)(min_over_time(disk_free{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "{{ host }}:{{ path }}"
    }
   ]
  },
  {
   "title": "Disk i/o",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(rate(diskio_read_bytes{project=\"$project\", service=\"$service\"}[$__rate_interval])) ",
     "legendFormat": "{{ host }}.read"
    },
    {
     "expr": "avg by (host)(rate(diskio_write_bytes{project=\"$project\", service=\"$service\"}[$__rate_interval])) * -1",
     "legendFormat": "{{ host }}.write"
    }
   ]
  },
  {
   "title": "Data disk usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (path,host,path)(max_over_time(disk_used{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(cpu_usage_iowait{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(rate(net_bytes_recv{project=\"$project\", service=\"$service\"}[$__rate_interval])) ",
     "legendFormat": "{{ host }}.rx"
    },
    {
     "expr": "avg by (host)(rate(net_bytes_sent{project=\"$project\", service=\"$service\"}[$__rate_interval])) * -1",
     "legendFormat": "{{ host }}.tx"
    }
   ]
  },
  {
   "title": "Network (sum of all nodes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(net_bytes_recv{project=\"$project\", service=\"$service\"}[$__rate_interval])) ",
     "legendFormat": "rx"
    },
    {
     "expr": "sum(rate(net_bytes_sent{project=\"$project\", service=\"$service\"}[$__rate_interval])) * -1",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "TCP connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (host)(sum_over_time(netstat_tcp_established{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "TCP socket state total on all nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(netstat_tcp_close{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "tcp_close"
    },
    {
     "expr": "sum(sum_over_time(netstat_tcp_close_wait{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "tcp_close_wait"
    },
    {
     "expr": "sum(sum_over_time(netstat_tcp_closing{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "tcp_closing"
    },
    {
     "expr": "sum(sum_over_time(netstat_tcp_established{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "tcp_established"
    },
    {
     "expr": "sum(sum_over_time(netstat_tcp_fin_wait1{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "tcp_fin_wait1"
    },
    {
     "expr": "sum(sum_over_time(netstat_tcp_fin_wait2{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "tcp_fin_wait2"
    },
    {
     "expr": "sum(sum_over_time(netstat_tcp_last_ack{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "tcp_last_ack"
    }
   ]
  },
  {
   "title": "Kafka metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Inbound messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(rate(kafka_server_BrokerTopicMetrics_MessagesInPerSec_Count{project=\"$project\", service=\"$service\"}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Fetch requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(rate(kafka_network_RequestMetrics_RequestsPerSec_Count{project=\"$project\", service=\"$service\"}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Failed fetch requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "max by (host)(rate(kafka_server_BrokerTopicMetrics_FailedFetchRequestsPerSec_Count{project=\"$project\", service=\"$service\"}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by (host,request)(rate(kafka_network_RequestMetrics_RequestsPerSec_Count{project=\"$project\", service=\"$service\"}[$__rate_interval])) ",
     "legendFormat": "{{ host }}.{{ request }}"
    }
   ]
  },
  {
   "title": "Kafka log cleaner: time since last run",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(kafka_log_LogCleanerManager_time_since_last_run_ms_Value{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Bytes in",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "max by (host)(rate(kafka_server_BrokerTopicMetrics_BytesInPerSec_Count{project=\"$project\", service=\"$service\"}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Bytes out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "max by (host)(rate(kafka_server_BrokerTopicMetrics_BytesOutPerSec_Count{project=\"$project\", service=\"$service\"}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Underreplicated partitions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(max_over_time(kafka_server_ReplicaManager_UnderReplicatedPartitions_Value{project=\"$project\", service=\"$service\"}[$__interval])) "
    }
   ]
  },
  {
   "title": "Delayed operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max by (host,delayedoperation)(max_over_time(kafka_server_DelayedOperationPurgatory_NumDelayedOperations_Value{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "{{ host }}.{{ delayedOperation }}"
    }
   ]
  },
  {
   "title": "Purgatory size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max by (host,delayedoperation)(max_over_time(kafka_server_DelayedOperationPurgatory_PurgatorySize_Value{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "{{ host }}.{{ delayedOperation }}"
    }
   ]
  },
  {
   "title": "ISR expands",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "max by (host)(rate(kafka_server_ReplicaManager_IsrExpandsPerSec_Count{project=\"$project\", service=\"$service\"}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "ISR shrinks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 48 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "max by (host)(rate(kafka_server_ReplicaManager_IsrShrinksPerSec_Count{project=\"$project\", service=\"$service\"}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Handler threads idle",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(kafka_server_KafkaRequestHandlerPool_RequestHandlerAvgIdlePercent_OneMinuteRate{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Network threads idle",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 55 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(kafka_network_SocketServer_NetworkProcessorAvgIdlePercent_Value{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Leader election rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(rate(kafka_controller_ControllerStats_LeaderElectionRateAndTimeMs_Count{project=\"$project\", service=\"$service\"}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Unclean leader elections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 55 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(rate(kafka_controller_ControllerStats_UncleanLeaderElectionsPerSec_Count{project=\"$project\", service=\"$service\"}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Consumer group lags",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (name)(avg_over_time(kafka_consumer_group_rep_lag{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Java metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(java_lang_Memory_used{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Garbage collection count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 70 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(rate(java_lang_GarbageCollector_G1_Young_Generation_CollectionCount{project=\"$project\", service=\"$service\"}[$__rate_interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Garbage collection duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (host)(avg_over_time(java_lang_GarbageCollector_G1_Young_Generation_CollectionTime{project=\"$project\", service=\"$service\"}[$__interval])) ",
     "legendFormat": "{{ host }}"
    }
   ]
  }
 ]
}